name: Build Virtual Keyboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore -r win-x64

    - name: Build
      run: dotnet build --configuration Release --no-restore -r win-x64

    - name: Publish
      run: dotnet publish --configuration Release --no-restore -r win-x64 --self-contained true -p:PublishSingleFile=false -p:PublishTrimmed=false

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualKeyboard-x64
        path: bin/Release/net8.0-windows10.0.19041.0/win-x64/publish/